-- Drop procedures that have parameter changes
DROP PROCEDURE IF EXISTS sp_createHome(VARCHAR, VARCHAR, UUID, VARCHAR, VARCHAR) CASCADE;
DROP PROCEDURE IF EXISTS sp_addUserToHome(VARCHAR, VARCHAR, VARCHAR) CASCADE;